export const studyAbroutProgram = {
    title: 'How To Pick Your Study-Abroad Program?',
    bodyPart01: 'It’s a far-away-from-home program and you would wish you could feel at home while you choose your country to study! The first thing on your list would be to research, learn, and research again the universities, programs, scholarships, fees, and the list goes on. But what is more important to consider would be the benefits that you can leverage out of your study-abroad program. Connecting with a program that interests you the most and has been linked to your studies so far would do the job. An alumni contact can aid you in their experiences. But there again is the strenuousness in culling between what is right and what is just an advertisement paradigm. So, it is always wise to connect to the consultant who excels in the respective business!',
    bodyPart02: 'In conjunction with the above, it is always wise to choose a country that excels in your area of interest, for your study abroad program and also with career opportunities and cost-effectiveness. Considering the major countries out there that offer international education programs, the Japanese education system is a top-drawer. Comparatively lower academic fees and generous scholarship programs are the major endearments. Unstinting and generous scholarships provided by the Japanese Government, the universities, corporations, as well as other organizations such as the Japan Student Services Organization (JASSO) lend a helping hand to back the living expenses of the student.'
};
export const WhoLearnJapaneseLanguage = {
    title: 'Who Must Learn the Japanese Language?',
    bodyPart01: 'It’s a far-away-from-home program and you would wish you could feel at home while you choose your country to study! The first thing on your list would be to research, learn, and research again the universities, programs, scholarships, fees, and the list goes on. But what is more important to consider would be the benefits that you can leverage out of your study-abroad program. Connecting with a program that interests you the most and has been linked to your studies so far would do the job. An alumni contact can aid you in their experiences. But there again is the strenuousness in culling between what is right and what is just an advertisement paradigm. So, it is always wise to connect to the consultant who excels in the respective business!',
    bodyPart02: 'In conjunction with the above, it is always wise to choose a country that excels in your area of interest, for your study abroad program and also with career opportunities and cost-effectiveness. Considering the major countries out there that offer international education programs, the Japanese education system is a top-drawer. Comparatively lower academic fees and generous scholarship programs are the major endearments. Unstinting and generous scholarships provided by the Japanese Government, the universities, corporations, as well as other organizations such as the Japan Student Services Organization (JASSO) lend a helping hand to back the living expenses of the student.'
};
export const JapaneseLanguageProficiencyTes = {
    title: 'The Japanese Language Proficiency Test (JLPT)',
    bodyPart01: 'It’s a far-away-from-home program and you would wish you could feel at home while you choose your country to study! The first thing on your list would be to research, learn, and research again the universities, programs, scholarships, fees, and the list goes on. But what is more important to consider would be the benefits that you can leverage out of your study-abroad program. Connecting with a program that interests you the most and has been linked to your studies so far would do the job. An alumni contact can aid you in their experiences. But there again is the strenuousness in culling between what is right and what is just an advertisement paradigm. So, it is always wise to connect to the consultant who excels in the respective business!',
    bodyPart02: 'In conjunction with the above, it is always wise to choose a country that excels in your area of interest, for your study abroad program and also with career opportunities and cost-effectiveness. Considering the major countries out there that offer international education programs, the Japanese education system is a top-drawer. Comparatively lower academic fees and generous scholarship programs are the major endearments. Unstinting and generous scholarships provided by the Japanese Government, the universities, corporations, as well as other organizations such as the Japan Student Services Organization (JASSO) lend a helping hand to back the living expenses of the student.'
};